# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73e9e97a4fbe4cdc488b67450e17701d5836a36e20d097a56e2debba3680e40c62c79e90051e7a86dfa50a01f7e7decfb7f628b344fec312a9d9a5c7c3830e19

test:
  secret_key_base: ab8df94aed41d6ee28f782564ad9a36b9e14bd0fca553da2876e179010a680789687f1d7c40d4f6c86ab9af2b69123b80d61139efe2353517785c190ef4d1ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
